"""
Django settings for hashflix project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # Define o Caminho Base (onde está o projeto)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bo%c&%i#h^29qj5&fo(ce1cw$@6(s+w*_838$vb&=11dl53iit' # Chave de Segurança (vai
# gerenciar várias coisas de segurança que já vem no Django)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Faz com que todas as mudanças realizadas no código reflitam no navegador

ALLOWED_HOSTS = [] # São os Hosts que vão ficar permitidos


# Application definition

# Apps Instalados
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filme',
    'crispy_forms',
    'crispy_bootstrap5',
]

# Processo de Meio de Caminho
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hashflix.urls' # Arquivo com os Links que comandam o Site

# Local do Projeto que vai ficar os Arquivos HTML
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'filme.novos_context.lista_filmes_recentes',
                'filme.novos_context.lista_filmes_em_alta',
                'filme.novos_context.filme_destaque'
            ],
        },
    },
]

WSGI_APPLICATION = 'hashflix.wsgi.application' # Arquivo para Configuração de Servidor


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Banco de Dados
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# Modelo que vai Gererenciar a Autenticação do Usuário
AUTH_USER_MODEL = "filme.Usuario"
# Validadores de Senha
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# O Idioma do Administrativo do Django
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Diz onde vão ficar os Arquivos de Imagem (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Define a Chave Primária das Tabelas do Banco de Dados
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações para Usuários não Logados
LOGIN_REDIRECT_URL = 'filme:homefilmes' # Página default que o Usuário vai ser Redirecionado Após Fazer o Login (O
# Django já faz o Redirecionamento Inteligente Automaticamente)
LOGIN_URL = 'filmes:login' # Página que o Usuário vai Fazer o Login

# Configurações para o Formulário com o Bootstrap
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"